"""add manual debts

Revision ID: 015ddc7b88cd
Revises: bbc08812ed2e
Create Date: 2026-02-12 02:42:05.040848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015ddc7b88cd'
down_revision = 'bbc08812ed2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ntype', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
