"""add order sheet sync fields

Revision ID: 2151068a7a1a
Revises: f89c9a68c7de
Create Date: 2026-02-12 01:17:23.361738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2151068a7a1a'
down_revision = 'f89c9a68c7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sheet_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sheet_last_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('sheet_last_error')
        batch_op.drop_column('sheet_sent_at')
        batch_op.drop_column('sheet_sent')

    # ### end Alembic commands ###
