"""add quick sale discount fields to pos_session

Revision ID: 301ee390b416
Revises: 015ddc7b88cd
Create Date: 2026-04-11 16:25:35.311118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301ee390b416'
down_revision = '015ddc7b88cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('can_manage_bookings', sa.BOOLEAN(), nullable=True),
    sa.Column('can_manage_products', sa.BOOLEAN(), nullable=True),
    sa.Column('can_manage_orders', sa.BOOLEAN(), nullable=True),
    sa.Column('can_manage_stadiums', sa.BOOLEAN(), nullable=True),
    sa.Column('can_manage_settings', sa.BOOLEAN(), nullable=True),
    sa.Column('can_view_reports', sa.BOOLEAN(), nullable=True),
    sa.Column('can_access_dashboard', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
