"""add booking sheet sync fields

Revision ID: f89c9a68c7de
Revises: 41365c6d9013
Create Date: 2026-02-12 00:01:21.931788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89c9a68c7de'
down_revision = '41365c6d9013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sheet_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sheet_last_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('sheet_last_error')
        batch_op.drop_column('sheet_sent_at')
        batch_op.drop_column('sheet_sent')

    # ### end Alembic commands ###
